### ISSUE TITLE
"TypeError :'NoneType' object is not subscriptable" when using .addTransformation(())

### ISSUE THREAD

**Issue by cepm-nate** [mstamy2/PyPDF3#14]
Trying to use the addTransformation function always ends up with an error:
````
Traceback (most recent call last):
  File "thepath/align.py", line 13, in <module>
    output.addPage(input1.getPage(1).addTransformation((1, 0, 0, 1, 0.5, 0.5)))
  File "C:\Users\xxxxx\AppData\Local\Programs\Python\Python38\lib\site-packages\PyPDF3\pdf.py", line 138, in addPage
    self._addPage(page, list.append)
  File "C:\Users\xxxxx\AppData\Local\Programs\Python\Python38\lib\site-packages\PyPDF3\pdf.py", line 123, in _addPage
    assert page["/Type"] == "/Page"
TypeError: 'NoneType' object is not subscriptable
````

Here's the code:
````
from PyPDF3 import PdfFileWriter, PdfFileReader

output = PdfFileWriter()
input1 = PdfFileReader(open("sample_input.pdf", "rb"))

# print how many pages input1 has:
print("sample has %d pages." % input1.getNumPages())

# add page 1 from input1 to output document, unchanged
output.addPage(input1.getPage(0))

# offset page 2
output.addPage(input1.getPage(1).addTransformation((1, 0, 0, 1, 0.5, 0)))

# finally, write "output" to document-output.pdf
outputStream = file("sample-output.pdf", "wb")
output.write(outputStream)
````

My goal: offset every other page by exactly 0.05290667 inches to the right. Eventually I will get to writing a simple loop, but for now I'd like to at least get the transformation function working. Anyone have any idea?

I also hunted for any code or examples showing .addTransformation(()) usage, but couldn't find any. Does someone have a simple sample?

**Comment by cepm-nate** [comment]
Here's how I solved it:
````
# offset page 2
page2 = input1.getPage(1)
page2.addTransformation((1, 0, 0, 1, ptOffset, 0))
output.addPage(page2)
````
Note that this is NOT mentioned in the docs. Apparently the .addTransformation function does NOT return the page, the same as the other pageObject functions do.
