### ISSUE TITLE
PyPDF2.utils.PdfReadError: Could not find object.

### ISSUE THREAD

**Issue by gonultasbu** [mstamy2/PyPDF3#7]
On some PDF files the PdfFileMerger(strict=False).write() gives the following error after merging.
```
PdfReadWarning: Object 225 0 not defined. [pdf.py:1629]
Traceback (most recent call last):
  File "/home/mert/Desktop/pdf_merge/pdf_merge.py", line 30, in <module>
    merger.write(fout)
  File "/home/mert/anaconda3/envs/pdf_merge/lib/python3.6/site-packages/PyPDF2/merger.py", line 230, in write
    self.output.write(fileobj)
  File "/home/mert/anaconda3/envs/pdf_merge/lib/python3.6/site-packages/PyPDF2/pdf.py", line 482, in write
    self._sweepIndirectReferences(externalReferenceMap, self._root)
  File "/home/mert/anaconda3/envs/pdf_merge/lib/python3.6/site-packages/PyPDF2/pdf.py", line 571, in _sweepIndirectReferences
    self._sweepIndirectReferences(externMap, realdata)
  File "/home/mert/anaconda3/envs/pdf_merge/lib/python3.6/site-packages/PyPDF2/pdf.py", line 547, in _sweepIndirectReferences
    value = self._sweepIndirectReferences(externMap, value)
  File "/home/mert/anaconda3/envs/pdf_merge/lib/python3.6/site-packages/PyPDF2/pdf.py", line 571, in _sweepIndirectReferences
    self._sweepIndirectReferences(externMap, realdata)
  File "/home/mert/anaconda3/envs/pdf_merge/lib/python3.6/site-packages/PyPDF2/pdf.py", line 547, in _sweepIndirectReferences
    value = self._sweepIndirectReferences(externMap, value)
  File "/home/mert/anaconda3/envs/pdf_merge/lib/python3.6/site-packages/PyPDF2/pdf.py", line 556, in _sweepIndirectReferences
    value = self._sweepIndirectReferences(externMap, data[i])
  File "/home/mert/anaconda3/envs/pdf_merge/lib/python3.6/site-packages/PyPDF2/pdf.py", line 571, in _sweepIndirectReferences
    self._sweepIndirectReferences(externMap, realdata)
  File "/home/mert/anaconda3/envs/pdf_merge/lib/python3.6/site-packages/PyPDF2/pdf.py", line 547, in _sweepIndirectReferences
    value = self._sweepIndirectReferences(externMap, value)
  File "/home/mert/anaconda3/envs/pdf_merge/lib/python3.6/site-packages/PyPDF2/pdf.py", line 577, in _sweepIndirectReferences
    newobj = data.pdf.getObject(data)
  File "/home/mert/anaconda3/envs/pdf_merge/lib/python3.6/site-packages/PyPDF2/pdf.py", line 1631, in getObject
    raise utils.PdfReadError("Could not find object.")
PyPDF2.utils.PdfReadError: Could not find object.

Process finished with exit code 1
```
Example PDF given in the attachment.

[textDetection.pdf](https://github.com/gonultasbu/pdf_merge/files/2453712/textDetection.pdf)

Example code 

https://github.com/gonultasbu/pdf_merge/blob/master/pdf_merge.py

edit: same issue is apparent for PyPDF2 and PyPDF3 both.

**Comment by gonultasbu** [comment]
The issue is prevalent on the latest pip version, update your PyPDF2 from GitHub and it should be gone.

**Comment by gonultasbu** [comment]
here is a workaround posted:

https://stackoverflow.com/a/52687771/10405090

**Comment by GoingMyWay** [comment]
This error is nasty.

**Comment by GoingMyWay** [comment]
This error is pervasive and it is hard to debug, I don't know why. Sometimes it can, sometimes it can't work.

**Comment by ali-layken** [comment]
That workaround should get pushed to master.

**Comment by gonultasbu** [comment]
The repo seems to be unmaintaned.

**Comment by mishawakerman** [comment]
@gonultasbu - we're looking to incorporate your workaround to get around this issue but are not sure about the consequences. It looks like an error is simply being ignored and an intentional, one would assume, conditional being uncommitted. Do you have an understanding of _why__ this fixes the issue and if it will result in content being removed from a document?

**Comment by gonultasbu** [comment]
@mishawakerman, I think the commented conditional should be uncommented in any case, looking at the code I don't see any point in throwing an error after a warning, unless it's run in strict mode. Therefore, I made an educated guess and assumed that this is a typo that somehow went through.

The ignored error part is tricky, it looks like it's something related to the encryption and pdf objects. Unfortunately I lack the sufficient knowledge about them.

**Comment by mishawakerman** [comment]
Thanks for the prompt reply. On testing, we found that we only needed to do the second (uncomment the `#if self.strict:`) change to avoid the issue.

**Comment by gonultasbu** [comment]
@mishawakerman I'm glad you managed to solve the issue! I'm fairly sure that the objects also caused some issues on certain files, make sure you have some other test cases.

In any case, it's of course better that you stick to the original implementation as much as you can.

**Comment by metaljoe** [comment]
I've had this exception raised by an incremental PDF generated in Adobe Photoshop Lightroom by a customer. We have an automated process that deals with a lot of PDFs and image files during the day.

Uncommenting the conditional does allow the file to save, albeit with three PdfReadWarnings (e.g. "PdfReadWarning: Object 154 0 not defined"). However, the first page of the output is missing content (presumably due to the three missing objects).

Interestingly, preprocessing the PDF with ghostscript generates a copy of the file that doesn't raise any warnings and doesn't lose content. It's not an ideal solution, and I'd rather PyPDF2 loaded and saved the file without. I'd be interested to know if gs is just handling the situation better, or there's a deeper problem when reading the file in PyPDF2.

**Comment by gonultasbu** [comment]
@metaljoe the type of the missing content can perhaps give an idea about the issue.

**Comment by metaljoe** [comment]
@gonultasbu I'll take a more in-depth look to see if I can spot something. I can't distribute the client's PDF publicly unfortunately. As a starting point from memory: the first page, which came out blank when saved by PyPDF2, was missing at least one image that filled the page.
